import type { ApiMovie } from "shared";

export const moviesData: ApiMovie[] = [
	{
		adult: false,
		backdrop_path: "/ygOR390GzOX5Quv0kAAcUNDG7fp.jpg",
		genre_ids: [12, 28, 27],
		id: 1511789,
		original_language: "en",
		original_title: "Captain Hook - The Cursed Tides",
		overview:
			"In the aftermath of a devastating defeat by his archnemesis Admiral Smee, the notorious Captain James Hook finds refuge in the coastal town of Eldritch Landing, where he forms an unlikely alliance with Silas Blackweather, a local blacksmith seeking retribution for his sister's murder. As they evade Smee's Redcoat Soldiers in the island's dense woodland, ruthless sword fights, ancient curses and conflicting motives will challenge their shared quest for revenge. Together, Hook and Silas navigate uncharted waters to confront the treacherous Admiral Smee, embarking on a journey that will redefine Captain Hook's enduring legacy.",
		popularity: 377.43,
		poster_path: "/bcP7FtskwsNp1ikpMQJzDPjofP5.jpg",
		release_date: "2025-07-11",
		title: "Captain Hook - The Cursed Tides",
		video: false,
		vote_average: 4.55,
		vote_count: 20,
	},
	{
		adult: false,
		backdrop_path: "/2yo2k8CmgZxfBQYAZ8TnHIYzEme.jpg",
		genre_ids: [28, 80, 53],
		id: 1072699,
		original_language: "pl",
		original_title: "Druga Furioza",
		overview:
			"In the wake of murder, new Furioza leader Golden claims the reins of his violent and formidable hooligan gang and takes on a new focus across borders.",
		popularity: 302.0473,
		poster_path: "/dbe1zKVKNBIczdmRcm7jxEphYLz.jpg",
		release_date: "2025-10-14",
		title: "Inside Furioza",
		video: false,
		vote_average: 6.657,
		vote_count: 35,
	},
	{
		adult: false,
		backdrop_path: "/qcDDn7WeKBenM4nLlOPXAeJ4hpg.jpg",
		genre_ids: [53, 28, 12],
		id: 1280450,
		original_language: "en",
		original_title: "Stolen Girl",
		overview:
			"In 1993, Maureen’s six-year-old daughter Amina is snuck out of the country by her ex-husband, Karim. After years of unsuccessful attempts to find her, Maureen intersects with a professional retriever of internationally abducted children who promises to help her find Amina in exchange for her collaboration.",
		popularity: 294.0708,
		poster_path: "/fZlNXEHZsBp7unqw009MeBbMv87.jpg",
		release_date: "2025-09-04",
		title: "Stolen Girl",
		video: false,
		vote_average: 6.611,
		vote_count: 36,
	},
	{
		adult: false,
		backdrop_path: "/42xAe6kVeTjml9Tww6vRoWa5tay.jpg",
		genre_ids: [28, 18, 53],
		id: 861451,
		original_language: "kn",
		original_title: "Martin",
		overview:
			"Martin revolves around Lt. Brigadier Arjun Saxena, whose journey takes him from Pakistan to India to discover his real identity and fight against black market dealers, who are involved with terrorists to orchestrate massive attacks in the country.",
		popularity: 271.658,
		poster_path: "/bYe2ZjUhb4Kje0BpWE6kN34u2hv.jpg",
		release_date: "2024-10-11",
		title: "Martin",
		video: false,
		vote_average: 2.1,
		vote_count: 8,
	},
	{
		adult: false,
		backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
		genre_ids: [16, 28, 14, 53],
		id: 1311031,
		original_language: "ja",
		original_title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
		overview:
			"The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.",
		popularity: 261.8345,
		poster_path: "/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg",
		release_date: "2025-07-18",
		title: "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
		video: false,
		vote_average: 7.785,
		vote_count: 477,
	},
	{
		adult: false,
		backdrop_path: "/1leYKN0DPNffpldGnCWnbXaiWoD.jpg",
		genre_ids: [28, 53],
		id: 1305717,
		original_language: "en",
		original_title: "Hunting Grounds",
		overview:
			"Desperate to find refuge for her children, Chloe Marvino runs away from her Mafia tied husband, and finds shelter in a cabin with a recluse drifter named Jake. But as her husband's henchmen draw closer to her, it turns out that Jake is the biggest enemy of them all.",
		popularity: 250.7735,
		poster_path: "/cgZjpqRQt9sk6XMCwZ3B1NPAaoy.jpg",
		release_date: "2025-05-16",
		title: "Hunting Grounds",
		video: false,
		vote_average: 0,
		vote_count: 0,
	},
	{
		adult: false,
		backdrop_path: "/5jHMDT9Jpu8U9ArKOLGyphhl5JF.jpg",
		genre_ids: [28, 35, 878],
		id: 338969,
		original_language: "en",
		original_title: "The Toxic Avenger Unrated",
		overview:
			"When a downtrodden janitor, Winston Gooze, is exposed to a catastrophic toxic accident, he’s transformed into a new kind of hero: The Toxic Avenger. Now, Toxie must rise from outcast to savior, taking on ruthless corporate overlords and corrupt forces who threaten his son, his friends, and his community.",
		popularity: 147.7848,
		poster_path: "/sIonGSpGNtH72OzbJllPOEMNjVU.jpg",
		release_date: "2025-08-28",
		title: "The Toxic Avenger Unrated",
		video: false,
		vote_average: 6.4,
		vote_count: 143,
	},
	{
		adult: false,
		backdrop_path: "/5A01YSCPYoCOZOhh9tU7F3Htxkf.jpg",
		genre_ids: [28, 14, 27, 53],
		id: 793387,
		original_language: "ko",
		original_title: "거룩한 밤: 데몬 헌터스",
		overview:
			"When a devil-worshipping criminal network plunges Seoul into chaos, the police turn to Holy Night—a trio of supernatural demon hunters—to restore order and defeat the rising evil.",
		popularity: 143.524,
		poster_path: "/v3Mo77Qjp6pctpD4eJaNT6kFRSB.jpg",
		release_date: "2025-04-30",
		title: "Holy Night: Demon Hunters",
		video: false,
		vote_average: 6.611,
		vote_count: 54,
	},
	{
		adult: false,
		backdrop_path: "/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg",
		genre_ids: [28, 12, 53, 80],
		id: 7451,
		original_language: "en",
		original_title: "xXx",
		overview:
			'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
		popularity: 143.1813,
		poster_path: "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
		release_date: "2002-08-09",
		title: "xXx",
		video: false,
		vote_average: 5.964,
		vote_count: 4592,
	},
	{
		adult: false,
		backdrop_path: "/pKIRUTnwY3YYU9urSdsuobdcliP.jpg",
		genre_ids: [28, 12, 53],
		id: 1109086,
		original_language: "hi",
		original_title: "वॉर 2",
		overview:
			"Years ago Agent Kabir went rogue, became India’s greatest villain ever.  As he descends further into the deepest shadows... India sends its deadliest, most lethal agent after him, Agent Vikram  A Special Units Officer who is more than Kabir’s equal and a relentless Terminator driven by his own demons, determined to put a bullet into Kabir’s skull.",
		popularity: 140.4594,
		poster_path: "/2Yc8Kl2ldPpDzLrG2M5Ddv62FXB.jpg",
		release_date: "2025-08-13",
		title: "War 2",
		video: false,
		vote_average: 5.258,
		vote_count: 31,
	},
	{
		adult: false,
		backdrop_path: "/ax2qCKU6tUhdkStiCnrDdXKA5xC.jpg",
		genre_ids: [28, 12],
		id: 1086910,
		original_language: "en",
		original_title: "The Lost Princess",
		overview:
			"After an Ayahuasca vision transports him to a haunted castle, Alec meets Hanna who tales him the story of her mother's forced marriage and how the forbidden passion with her father was in danger when the princess pregnancy became obvious",
		popularity: 135.4042,
		poster_path: "/31S2ISsDtbnxb0kuXZl1SxSMD0K.jpg",
		release_date: "2025-10-16",
		title: "The Lost Princess",
		video: false,
		vote_average: 6.323,
		vote_count: 31,
	},
	{
		adult: false,
		backdrop_path: "/a6RkQIOZ6wThQOEDv6lHsfH53hD.jpg",
		genre_ids: [28, 80, 53],
		id: 1186350,
		original_language: "ml",
		original_title: "മാർക്കോ",
		overview:
			"The adoptive son of the Adattu family, Marco, sets off on a ruthless quest for vengeance after his brother is brutally murdered, finding only betrayal, loss and unimaginable brutality at every step.",
		popularity: 129.0635,
		poster_path: "/il3ao5gcF6fZNqo1o9o7lusmEyU.jpg",
		release_date: "2024-12-20",
		title: "Marco",
		video: false,
		vote_average: 6.5,
		vote_count: 75,
	},
	{
		adult: false,
		backdrop_path: "/538U9snNc2fpnOmYXAPUh3zn31H.jpg",
		genre_ids: [28, 12, 53],
		id: 575265,
		original_language: "en",
		original_title: "Mission: Impossible - The Final Reckoning",
		overview:
			"Ethan Hunt and team continue their search for the terrifying AI known as the Entity — which has infiltrated intelligence networks all over the globe — with the world's governments and a mysterious ghost from Hunt's past on their trail. Joined by new allies and armed with the means to shut the Entity down for good, Hunt is in a race against time to prevent the world as we know it from changing forever.",
		popularity: 119.0939,
		poster_path: "/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg",
		release_date: "2025-05-17",
		title: "Mission: Impossible - The Final Reckoning",
		video: false,
		vote_average: 7.273,
		vote_count: 1981,
	},
	{
		adult: false,
		backdrop_path: "/bWF5ImUscXXYia8owpm8coadR4m.jpg",
		genre_ids: [28, 27, 10752],
		id: 1257009,
		original_language: "en",
		original_title: "Primitive War",
		overview:
			"During the Vietnam War, a recon unit ventures to an isolated jungle valley to uncover the fate of a missing platoon. They soon find themselves in a fight for their lives against an unexpected enemy — prehistoric dinosaurs.",
		popularity: 110.5542,
		poster_path: "/nWBqU5YXmDVJWWEDJ4u3ZSseNVL.jpg",
		release_date: "2025-08-21",
		title: "Primitive War",
		video: false,
		vote_average: 6.868,
		vote_count: 125,
	},
	{
		adult: false,
		backdrop_path: "/eGX66zonvc4bXg3rM08RUxdYSDx.jpg",
		genre_ids: [878, 12, 28],
		id: 1061474,
		original_language: "en",
		original_title: "Superman",
		overview:
			"Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
		popularity: 106.8958,
		poster_path: "/wPLysNDLffQLOVebZQCbXJEv6E6.jpg",
		release_date: "2025-07-09",
		title: "Superman",
		video: false,
		vote_average: 7.436,
		vote_count: 3649,
	},
	{
		adult: false,
		backdrop_path: "/yGByIyqgJerCw7AAphTrTAlrdkJ.jpg",
		genre_ids: [28, 10752, 53, 36],
		id: 1328803,
		original_language: "en",
		original_title: "Prisoner of War",
		overview:
			"British RAF Wing Commander James Wright is captured by the Japanese during WWII and forced to fight in brutal hand-to-hand combat. The Japanese soldiers get more than they bargained for when Wright’s years of martial arts training in Hong Kong prove him to be a formidable opponent.",
		popularity: 95.4973,
		poster_path: "/1XET89sjRm9mUuHXhGIlKTNd5uD.jpg",
		release_date: "2025-09-19",
		title: "Prisoner of War",
		video: false,
		vote_average: 6.968,
		vote_count: 94,
	},
	{
		adult: false,
		backdrop_path: "/np0dsehLDdbfyHFRtqCiL1GR0TQ.jpg",
		genre_ids: [878, 12, 28],
		id: 533533,
		original_language: "en",
		original_title: "TRON: Ares",
		overview:
			"A highly sophisticated Program called Ares is sent from the digital world into the real world on a dangerous mission, marking humankind's first encounter with A.I. beings.",
		popularity: 94.493,
		poster_path: "/chpWmskl3aKm1aTZqUHRCtviwPy.jpg",
		release_date: "2025-10-08",
		title: "TRON: Ares",
		video: false,
		vote_average: 6.4,
		vote_count: 282,
	},
	{
		adult: false,
		backdrop_path: "/yOFqBpJ0PEkBdQqalDEaeOiaKbz.jpg",
		genre_ids: [28, 80, 53],
		id: 1267319,
		original_language: "ko",
		original_title: "사마귀",
		overview:
			"Mantis, an ace assassin, returns to the contract killer industry after a hiatus, encountering his trainee friend Jae-yi and a retired legendary killer Dok-go, who now runs the organization.",
		popularity: 85.338,
		poster_path: "/x6WLRwwddFKattMseWL3m7Geskd.jpg",
		release_date: "2025-09-26",
		title: "Mantis",
		video: false,
		vote_average: 6.039,
		vote_count: 90,
	},
	{
		adult: false,
		backdrop_path: "/8fA0Gr4vJNPOd0jyqWKU7ef8DoH.jpg",
		genre_ids: [878, 12, 28],
		id: 1234821,
		original_language: "en",
		original_title: "Jurassic World Rebirth",
		overview:
			"Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
		popularity: 83.6919,
		poster_path: "/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg",
		release_date: "2025-07-01",
		title: "Jurassic World Rebirth",
		video: false,
		vote_average: 6.39,
		vote_count: 2339,
	},
	{
		adult: false,
		backdrop_path: "/wPSZXVqe84X8SINvJGiKYZhkSG1.jpg",
		genre_ids: [10752, 53, 28],
		id: 1009640,
		original_language: "en",
		original_title: "Valiant One",
		overview:
			"With tensions between North and South Korea, a US helicopter crashes on the North side. The survivors must work together to protect a civilian tech specialist and find their way out without the help of US military support.",
		popularity: 76.5187,
		poster_path: "/sT8Z14RDCAd6szzxzWFAU4xcMwg.jpg",
		release_date: "2025-01-30",
		title: "Valiant One",
		video: false,
		vote_average: 6.527,
		vote_count: 55,
	},
];
